<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;

class DatabaseSmartRecord extends Model
{
    protected $fillable = [
        'upload_batch_id',
        'source_row',
        'ref',
        'program_name',
        'sap_program_wbs_name',
        'project_name',
        'sap_project_wbs_name',
        'business_case_no',
        'main_wbs',
        'sub_wbs',
        'cost_centre',
        'pr_no',
        'po_no',
        'allocated_project_amount',
        'approval_year',
        'owner',
        'executor',
        'department',
        'strategic_driver',
        'level',
        'blank_1',
        'project_name_arabic',
        'contractor_designer_name',
        'contract_type',
        'original_contract_value',
        'vo_amount',
        'vo_pct',
        'advance_amount',
        'total_paid_amount',
        'invoiced_amount',
        'remaining_amount',
        'blank_2',
        'project_status',
        'stage_gate',
        'stage_gate_progress',
        'category_1_previous',
        'designer_category',
        'contractor_category',
        'program',
        'sub_program',
        'cm_category',
        'program_manager',
        'project_manager',
        'project_lead',
        'project_start_date',
        'project_finish_date',
        'original_duration',
        'suspension_date',
        'resumption_date',
        'revised_finish_date',
        'revised_duration',
        'planned_pct',
        'actual_pct',
        'sv',
        'ev',
        'pv',
        'ac',
        'spi',
        'cpi',
        'applicable_finish_date',
        'project_health',
        'blank_3',
        'brief_description',
        'engineering_pct',
        'procurement_pct',
        'construction_pct',
        'engineering_status_update',
        'procurement_status_update',
        'construction_status_update',
        'weekly_lookahead',
        'issues_concerns',
        'risks',
        'data_issue',
        'key_check',
        'last_updated_at',
    ];

    protected function casts(): array
    {
        return [
            'allocated_project_amount' => 'decimal:2',
            'original_contract_value' => 'decimal:2',
            'vo_amount' => 'decimal:2',
            'vo_pct' => 'decimal:6',
            'advance_amount' => 'decimal:2',
            'total_paid_amount' => 'decimal:2',
            'invoiced_amount' => 'decimal:2',
            'remaining_amount' => 'decimal:2',
            'project_start_date' => 'date',
            'project_finish_date' => 'date',
            'suspension_date' => 'date',
            'resumption_date' => 'date',
            'revised_finish_date' => 'date',
            'planned_pct' => 'decimal:6',
            'actual_pct' => 'decimal:6',
            'sv' => 'decimal:6',
            'ev' => 'decimal:2',
            'pv' => 'decimal:2',
            'ac' => 'decimal:2',
            'spi' => 'decimal:6',
            'cpi' => 'decimal:6',
            'applicable_finish_date' => 'date',
            'engineering_pct' => 'decimal:6',
            'procurement_pct' => 'decimal:6',
            'construction_pct' => 'decimal:6',
            'last_updated_at' => 'datetime',
        ];
    }

    public function uploadBatch(): BelongsTo
    {
        return $this->belongsTo(WorkbookUpload::class, 'upload_batch_id');
    }
}
